receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 100
    send_batch_max_size: 500
  
  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: yolo_analytics
    username: default
    password: ""
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    logs_table_name: otel_logs
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    create_schema: true
    
  debug:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse, debug]
    
    # Обробка метрик (тільки ClickHouse)
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse, debug]

  telemetry:
    logs:
      level: "info"
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888 
