apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: yolo_analytics
    basicAuth: false
    isDefault: true
    jsonData:
      username: default
      server: clickhouse
      port: 8123
      protocol: http
    secureJsonData:
      password: "" 