kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ray-cluster
nodes:
- role: control-plane
  extraPortMappings:
  # Standard web ports (might be useful for other services)
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=1Gi
        eviction-hard: memory.available<1.5Gi
        eviction-soft: memory.available<3Gi
        eviction-soft-grace-period: memory.available=60s
        eviction-minimum-reclaim: memory.available=500Mi
  extraMounts:
  - hostPath: /tmp/kubeflow-data
    containerPath: /data
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=1Gi
        eviction-hard: memory.available<1.5Gi
        eviction-soft: memory.available<3Gi
        eviction-soft-grace-period: memory.available=60s
        eviction-minimum-reclaim: memory.available=500Mi
