global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Системні метрики самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - системні метрики хоста (CPU, пам'ять)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']